spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  output:
    ansi:
      enabled: always
logging:
  level:
    org.hibernate.type: trace